services:
  php:
    build:
      context: .
      target: dev
    container_name: php_server
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "pgsql://laravel:laravel@db:5432/laravel"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
      - mailpit
    user: "1000:1000" 

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - vite

  vite:
    build:
      context: .
      target: dev
    container_name: vite_server
    working_dir: /var/www/html/Laravel_app
    ports:
      - "5173:5173"
    volumes:
      - ./Laravel_app:/var/www/html/Laravel_app
    command: sh -c "npm install && npm run dev"
    user: "1000:1000"

  db:
    image: postgres:16-alpine
    container_name: db_database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: laravel_redis

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: laravel_mailpit
    ports:
      - "8025:8025"

volumes:
  db_data:
  laravel_app:
